
CFLAGS := -Wall -O3 -ffast-math -msse -msse2 -mfpmath=sse -ftree-vectorize -fPIC -I../vamp-plugin-sdk/ -DUSE_PTHREADS

#CFLAGS := -g -fPIC -I../vamp-plugin-sdk

CXXFLAGS := $(CFLAGS)

VAMPSDK_DIR := ../vamp-plugin-sdk

PLUGIN_LDFLAGS := -lfftw3f -lfftw3 -shared -Wl,-Bsymbolic -Wl,-z,defs -Wl,--version-script=vamp-plugin.map -lpthread

PLUGIN_EXT := .so

include Makefile.inc


